#!/usr/bin/env ruby
require 'yaml'

# guess output_format from argv
def get_output_format(argv = ARGV)
  output_file = nil
  (argv || []).each_with_index do |a, i|
    next if a.nil?
    if a == "-o" || a == "--output"
      output_file = argv[i+1]
    elsif a.start_with?("--output=")
      output_file = a[9..-1]
    end
  end
  output_format = nil
  (argv || []).each_with_index do |a, i|
    next if a.nil?
    if a == "-t" || a == "--to"
      output_format = argv[i+1]
    elsif a.start_with?("--to=")
      output_format = a[5..-1]
    end
  end
  if output_format.nil?
    if !output_file.nil? && output_file.include?(".")
      output_format = output_file.split(".").last
      if ["pdf", "tex"].include? output_format
        output_format = "latex"
      end
    end
  end
  output_format
end

# parse argv to find: leading options, input file, and post-file args
# This respects options that take values (e.g. -t epub or --to=epub)
def parse_argv_for_input(argv)
  argv ||= []
  leading = []
  input_file = nil
  post = []
  i = 0
  while i < argv.length
    a = argv[i]
    break if a.nil?
    # explicit end-of-options
    if a == "--"
      i += 1
      if i < argv.length
        input_file = argv[i]
        post = argv[(i+1)..-1] || []
      end
      break
    end

    # if we already found input_file, remaining tokens are post
    if input_file
      post << a
      i += 1
      next
    end

    if a.start_with?("-")
      # options that take a separate value
      if ["-t","--to","-o","--output"].include?(a)
        leading << a
        if i+1 < argv.length
          leading << argv[i+1]
        end
        i += 2
      elsif a.include?("=")
        leading << a
        i += 1
      else
        # flag without value
        leading << a
        i += 1
      end
    else
      input_file = a
      i += 1
      post = argv[i..-1] || []
      break
    end
  end

  [leading, input_file, post]
end

def get_pandoc_opts()
  opts = %x(pandoc --bash-completion).scan(/opts\=\"([^"]*)/).first.first

  # strip the two preceding dashes and ignore one-letter variants
  opts.split(' ').map do |o|
    if o[0..1] == "--"
      o[2..-1]
    end
  end
end

# convert a meta-hash to an arguments-array
def get_args(meta)
  pandoc_opts = get_pandoc_opts()
  args = []
  meta.each do |key, val|
    # check whether `key` is an option that can be
    # used with the installed pandoc version
    if pandoc_opts.include? key
      opt = key
    else
      # since RMarkdown YAML uses e.g. `toc_depth` instead of `toc-depth`
      # try that as well:
      key = key.gsub('_', '-')
      if pandoc_opts.include? key
        opt = key
      end
    end

    if opt && val != false
      if val.is_a? Hash
        val.each do |k, v|
          args.push "--" ++ opt
          args.push k ++ "=" ++ v
        end
      elsif val.is_a? Array
        val.each do |v|
          args.push "--" ++ opt
          args.push v
        end
      else
        args.push "--" ++ opt
        if not (val.nil? || val.is_a?(TrueClass))
          # try to only include a value for an option that takes one
          args.push val.to_s
        end
      end
    end
  end

  if more_args = meta['pandoc_args']
    args.concat more_args
  end
  return args
end

def output_key_name()
  "output"
end

def data_dir_name()
  if ENV['APPDATA']
    # Windows
    File.join ENV['APPDATA'], "panrun"
  else
    # POSIX
    File.join Dir.home, ".panrun"
  end
end

def load_yaml(file_name)
  begin
    # try ruby v3 arguments
    YAML.load_file(file_name, permitted_classes:["Date"])
  rescue ArgumentError
    # fallback to ruby v2 arguments
    YAML.load_file(file_name)
  end
end

# try to load default YAML from other files and merge it with local YAML
def get_meta_from_other_file(meta, type=nil)
  if not type.is_a?(String)
    type = "default"
  end
  data_dir = data_dir_name()
  file_name = if [".", "..", "/", "\\"].include? type[0]
                if File.file? type
                  type
                else
                 abort "Could not find file #{type}"
                end
              else
                # look in ~/.panrun/
                name = File.join(data_dir, type + ".yaml")
                if File.file? name
                  name
                else
                  nil
                end
              end
  file_meta, args, file_top = if file_name && m = load_yaml(file_name)
                                  [ m[output_key_name] || {}, ["--metadata-file", file_name], (m.reject { |k,_| k == output_key_name }) ]
                                else
                                  [{}, [], {}]
                                end
  file_meta.each do |format, _|
    meta[format] = file_meta[format].merge( meta[format] || {} )
  end
  return [meta, args, file_top]
end


def apply_global_from(meta, top_from)
  return meta unless top_from
  meta.each do |format, val|
    val = {} unless val.is_a?(Hash)
    unless val.key?("from")
      val["from"] = top_from
    end
    meta[format] = val
  end
  meta
end


def build_pandoc_args(*args)
  # two calling conventions:
  #  - build_pandoc_args(argv_array)
  #  - build_pandoc_args(input_file, argv_array)
  if args.length == 1 && args[0].is_a?(Array)
    argv_array = args[0]
    leading_opts, input_file, post_file_args = parse_argv_for_input(argv_array)
  elsif args.length >= 2
    input_file = args[0]
    argv_array = args[1].is_a?(Array) ? args[1] : ARGV
    # find input_file index in argv_array
    idx = argv_array.index(input_file)
    if idx
      leading_opts = argv_array[0...idx]
      post_file_args = argv_array[(idx+1)..-1] || []
    else
      # fallback: no index found, try parsing normally
      leading_opts, input_file, post_file_args = parse_argv_for_input(argv_array)
    end
  else
    raise ArgumentError, "Invalid arguments for build_pandoc_args"
  end

  yaml = load_yaml(input_file) || {}
  doc_meta = yaml[output_key_name] || {}
  meta, file_arg, file_top = get_meta_from_other_file doc_meta, yaml["type"]
  # apply top-level `from` precedence
  top_from = yaml["from"] || (file_top && file_top["from"])
  apply_global_from(meta, top_from) if top_from

  # determine output format from provided argv_array
  output_format = get_output_format(argv_array)
  if output_format.nil?
    if meta.is_a?(Hash) && meta.first
      output_format = meta.first[0]
    else
      raise "Could not find any output format in YAML."
    end
  end

  # lookup format in meta, else try various rmarkdown formats
  meta_out = if meta[output_format]
               meta[output_format]
             elsif meta[output_format + "_document"]
               meta[output_format + "_document"]
             elsif output_format == "latex" && meta["pdf_document"]
               meta["pdf_document"]
             elsif meta[output_format + "_presentation"]
               meta[output_format + "_presentation"]
             else
               raise "Could not find YAML key for detected output format '#{output_format}'."
             end

  meta_args = get_args(meta_out)
  final_args = ["pandoc"] + (leading_opts || []) + [input_file] + meta_args + (file_arg || []) + (post_file_args || [])
  final_args
end

if __FILE__ == $0
  leading_opts, input_file, post_file_args = parse_argv_for_input(ARGV)
  if input_file.nil? || input_file[0] == "-"
    abort "Usage: panrun input.md [pandoc-options]\n\n"\
          "Looking for default.yaml etc. in #{data_dir_name}\n"\
          "For more info, see https://github.com/mb21/panrun"
  end

  args = build_pandoc_args(ARGV)

  STDERR.puts "panrun calling: " + args.join(' ')

  exec *args
end
